### ISSUE TITLE
`v1.0.3`版本没有`progress_max`属性

### ISSUE THREAD

**Issue by koala0x** [EthanCo/StripeProgressBar#1]
`
implementation 'com.github.EthanCo:StripeProgressBar:v1.0.3'
`
这个版本没有`progress_max`属性, 但是源码里做了这个属性功能,大佬是不是传错了包呢?
我自己下载了源码然后打了个`aar`包用上了, 挺好用的, 感谢大佬. @EthanCo

**Comment by EthanCo** [comment]
感谢反馈，确实存在这个问题，没打进去，已修复了
